GET http://localhost:3000/api/authors

###

GET http://localhost:3000/api/authors/1

###

POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "name": "Javier Moreno",
    "email": "j.moreno@email.com"
}

###

GET http://localhost:3000/api/categories